name: 🐳 ThinkLab Manager - Dockerfile Linter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  hadolint:
    name: 🦺 Hadolint Code Guard
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código do repositório
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4

      # 2. Executa a validação estática do Dockerfile contra as melhores práticas da comunidade
      - name: 📐 Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: 'Dockerfile'
          failure-threshold: 'error' # Só quebra o build se for uma má prática gravíssima